spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fruit}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:123456}
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    generate-ddl: ${JPA_GENERATE_DDL:false}
