spring:
  main:
    allow-circular-references: true
  profiles:
    active: local
  security:
    jwt:
      secret: ${JWT_SECRET:1ecd8e66-e5aa-42a3-b73f-ea24cc1fc088}
      expire: ${JWT_EXPIRE:86400000}


  datasource:
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1

app:
  services:
    minio:
      url: http://localhost:9000
      accessKey: admin
      secretKey: SlowV@123
      bucket: fruit

server:
  port: 1998