spring:
  main:
    allow-circular-references: true
  profiles:
    active: local
  security:
    jwt:
      secret: ${JWT_SECRET:1ecd8e66-e5aa-42a3-b73f-ea24cc1fc088}
      expire: ${JWT_EXPIRE:86400000}


  datasource:
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1

app:
  services:
    minio:
      url: ${MINIO_URL:http://localhost:9000}
      accessKey: ${MINIO_SERVER_ACCESS_KEY:admin}
      secretKey: ${MINIO_SERVER_SECRET_KEY:SlowV@123}
      bucket: fruit

server:
  port: 8080