spring:
  jpa:
    open-in-view: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  profiles:
    active: local
  security:
    jwt:
      secret: ${JWT_SECRET:1ecd8e66-e5aa-42a3-b73f-ea24cc1fc088}
      expire: ${JWT_EXPIRE:86400000}
    reset-token:
      expire: ${RESET_TOKEN_EXPIRE:90000}
      link: ${RESET_PASSWORD_LINK:http://localhost:4200/reset-password}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:sales.fruit.vh@gmail.com}
    password: ${MAIL_PASSWORD:!Viet1998}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: true

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:admin}

  datasource:
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1

app:
  services:
    minio:
      url: ${MINIO_URL:http://localhost:9000}
      accessKey: ${MINIO_SERVER_ACCESS_KEY:admin}
      secretKey: ${MINIO_SERVER_SECRET_KEY:SlowV@123}
      bucket: fruit

logging:
  level:
    root: ${LOG_LEVEL:info}
    ru.pflb.foundation.config.RequestResponseLoggingFilter: ${LOG_LEVEL_HTTP:trace}
    org:
      apache.kafka.clients.NetworkClient: ERROR
      hibernate: WARN

server:
  port: 8080