version: "3.7"

x-minio-common: &minio-common
  image: docker.io/bitnami/minio:2022
  environment:
    - MINIO_ROOT_USER=admin
    - MINIO_ROOT_PASSWORD=SlowV@123
    - MINIO_DISTRIBUTED_MODE_ENABLED=yes
    - MINIO_DISTRIBUTED_NODES=fruit-minio-1,fruit-minio-2,fruit-minio-3,fruit-minio-4
  networks:
    - backend


services:
  #  fruit-app:
  #    image: fruit
  #    networks:
  #      - backend
  #    environment:
  #      - MINIO_SERVER_ACCESS_KEY=minio-access-key
  #      - MINIO_SERVER_SECRET_KEY=minio-secret-key

  fruit-mysql:
    container_name: postgres-db
    image: postgres:13.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-fruit}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend
    restart: always

  fruit-minio-1:
    <<: *minio-common
    container_name: fruit-minio-1
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - data1:/data

  fruit-minio-2:
    <<: *minio-common
    container_name: fruit-minio-2
    volumes:
      - data2:/data

  fruit-minio-3:
    <<: *minio-common
    container_name: fruit-minio-3
    volumes:
      - data3:/data

  fruit-minio-4:
    <<: *minio-common
    container_name: fruit-minio-4
    volumes:
      - data4:/data


networks:
  backend:
    driver: bridge

volumes:
  postgres_volume:
    driver: local
  data1:
    driver: local
  data2:
    driver: local
  data3:
    driver: local
  data4:
    driver: local